app/main.py, app/models.py
- Creating Api point for KP
- #2
=> Api point for KP

app/knowledge_panels.py, app/main.py, app/models.py, tests/test_knowledge_panels.py, tests/test_main.py
- Implementing simple hunger game KP
- Add tests 
- #3
=> feat: Adding a knowledge panel for Hunger Games

app/knowledge_panels.py, app/main.py, app/models.py, app/off.py, tests/test_knowledge_panels.py, tests/test_utils.py
- Added knowledge panel for last Edits
- Updated mock test for taking parameter
- 
- #12
=> Added last_edits_kp

Makefile
=> refactor: Update Makefile

.github/workflows/generate-docs.yml, docs/README.md, mkdocs.yml
- Creating github page for docs
- #44
=> build: Github page for docs

docs/README.md
=> docs: Broken links in README.md

i18n/fr/LC_MESSAGES/knowledge-panel.po
hey, minor changes to fr translation
- 
- 
-
=> chore: Update knowledge-panel.po

app/knowledge_panels.py, app/main.py, app/models.py, app/off.py, template/item.html, tests/test_knowledge_panels.py, tests/test_main.py, tests/test_utils.py
* feat: the knowledge panels specs, specify to put all panels in a dict
* refactor: small improvements in hunger games panel
* test: add some more tests for edge cases
* test: avoid making external queries in tests
* fix: make panels ids consistents
=> feat: stick to knowledge panels spec

.github/workflows/release-please.yml, Dockerfile
release please must use a Personal Access Token to have the tag trigger action (and deliver to production).
See https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/84
=> ci: release please token

.github/workflows/container-deploy.yml
Add values for url in deploy configuration.
=> ci: fix deploy with new parameters

.github/workflows/container-build.yml
We need to build image on push to "main", the placeholder was not replaced :grimacing:
=> ci: fix container image build condition

.env, .github/workflows/container-deploy.yml, app/config.py, app/knowledge_panels.py, app/main.py
=> fix: staging deployment for off.net

app/exception_wrapper.py, app/knowledge_panels.py, app/main.py, app/off.py
- Remove expectation from [main.py](https://github.com/openfoodfacts/facets-knowledge-panels/blob/9b1c3562c67ac0fe40a7b017386ce6c592f95f9c/app/main.py#L115) and putting deep in the code 
- #85
=> fix: Sever side error

app/main.py
- Allow all origin (to avoid CORS issues)
=> fix: Allow all origin

app/knowledge_panels.py, app/off.py, template/item.html, tests/test_knowledge_panels.py
- Tweak the current HTML response to get a better preview in off-server
**Representations of how it would look on the serve side**
=> refactor: Tweak HTML template

app/knowledge_panels.py, app/models.py
- Now support Alpha2 code.
- This will make integration easy on off side.
=> feat: Now support alpha2 code

template/item.html
=> refactor: add panel id

app/knowledge_panels.py, app/off.py, tests/test_knowledge_panels.py, tests/test_main.py
- Changed data-quality URL to "data-quality-errors"
- [#8158](https://github.com/openfoodfacts/openfoodfacts-server/issues/8158)
=> refactor: Changed Data-quality Url

app/off.py
to avoid flooding logs with errors
fixes:
- #103
=> fix: avoid failing on known situations

app/off.py, i18n/en/LC_MESSAGES/knowledge-panel.po, i18n/fr/LC_MESSAGES/knowledge-panel.po, i18n/hi/LC_MESSAGES/knowledge-panel.po, i18n/knowledge-panel.pot, tests/test_knowledge_panels.py
=> fix: small change in .pot

app/off.py
=> refactor: use User-Agent

.github/workflows/crowdin.yml
=> fix: fix the crowdin branch

tests/test_dataquality_kp.py
` added test case for data quality `
Fixes #88
=> test:  added test cases for test_dataquality_kp

docs/how-to-guides/Project-setup-locally.md, docs/how-to-guides/Testing.md
Update docker-compose to docker compose in documentation :
- Project-setup-locally.md
- Testing.md
=> docs: Update docker-compose to docker compose in documentation

app/knowledge_panels.py, app/off.py, tests/test_dataquality_kp.py, tests/test_main.py
This PR fixes #171 based on the suggestion given in the issue.
=> fix: resolve JSON fetch failure in `data_quality_kp` method

README.md
- docs: Update README.md with figma for kp facets
=> docs: Update README.md with figma for kp facets
